(* begin-package-description
The Node package manages:

Intra- and inter-node coordination

end-package-description *)

(* begin-module-short-description
coordination within and between nodes.
end-module-short-description *)

(* begin-module-use-description
Module Nodes handles:

* Nothing yet. Node coordination eventually.

end-module-use-description *)
MODULE Nodes; 
  IMPORT SYSTEM, Kernel;

  CONST 

  TYPE 

  VAR 

BEGIN
END Nodes.
